language: swift
osx_image: xcode12
before_install:
  - gem install cocoapods -v '1.8.3'
install:
  - ./install_swiftlint.sh
script:
  - gem install travis
  - travis lint .travis.yml --no-interactive
  - swiftlint
  - xcodebuild clean build -workspace Example/TypographyKit.xcworkspace -scheme TypographyKit-Example -destination "platform=iOS Simulator,name=iPhone 11" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - pod lib lint --allow-warnings
